# Copy this file to .github/workflows/claude.yml in your repository
#
# Required setup:
# 1. Add CLAUDE_CODE_OAUTH_TOKEN to repository secrets
# 2. Adjust authorized_roles if needed

name: Claude Code

on:
  issue_comment:
    types: [created, edited]
  pull_request_review_comment:
    types: [created, edited]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    uses: simonheimlicher/spx-gh-actions/.github/workflows/claude.yml@main
    secrets:
      CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
    # Uncomment and modify to customize:
    # with:
    #   authorized_roles: '["OWNER", "MEMBER"]'
    #   mention_trigger: '@bot'
    #   concurrency_cancel: false
    #   allowed_tools: '--allowed-tools "Read,Grep,Glob,Bash(gh pr:*)"'
